id: P973F9FC2
initial_creation_type: ocr
source_metadata:
  volumes:
    3f960546369743d998325f9c5820073c:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: འཁོར་བ་ལས་ཡིད་ངེས་པར་འབྱུང་བར་བྱེད་པ་ཞེས་བྱ་བའི་གླུ།
      total_pages: 1902
      volume_number: 26
